loadDone = false

function onLoad()
	loadDone = true
end

function onCollisionEnter(info)
	if info and loadDone then
		local target = getObjectFromGUID(info.collision_object.guid)

		if target then
			if target.tag == "Deck" then
				local tmpObj = getObjectFromGUID(Global.getVar('settingsPannel_guid'))
				if tmpObj then
					Global.call('settingsPannelMakeButtons')
				end
			end
		end
	end
end